const faqItems = [
  {
    id: 1,
    title: "Differences between SQL and NoSQL",
    content: (
      <table className="table border-2 border-black lg:w-3/4">
        <thead>
          <tr>
            <th className="w-2"></th>
            <th className="w-1/2 text-center">SQL</th>
            <th className="text-center">NoSQL</th>
          </tr>
        </thead>
        <tbody>
          {[
            ["SQL is a domain-specific language used to query and manage data. Data is stored in collections or documents", "NoSQL stands for Not only SQL. It is a type of database that uses non-relational data structures, such as documents, graph databases, and key-value stores to store and retrieve data."],
            ["Stands for Structured Query Language", "Stands for Not Only SQL"],
            ["Relational database management system (RDBMS)", "Non-relational database management system"],
            ["Suitable for structured data with predefined schema", "Suitable for unstructured and semi-structured data"],
            ["Data is stored in tables with columns and rows", "Data is stored in collections or documents"],
          ].map((row, idx) => (
            <tr key={idx}>
              <th>{idx + 1}</th>
              <td>{row[0]}</td>
              <td>{row[1]}</td>
            </tr>
          ))}
        </tbody>
      </table>
    ),
  },
  {
    id: 2,
    title: "What is JWT? How does it work?",
    content: (
      <>
        <p>JSON Web Token (JWT) authentication is a stateless method of securely transmitting information between parties as a JavaScript Object Notation (JSON) object. It is often used to authenticate and authorize users in web applications and APIs.</p>
        <p className="font-semibold text-lg mt-3">Working process:</p>
        <p>JWT authorization uses a JWT to represent the user&lsquo;s identity and access rights. The JWT is usually generated by the authentication server after the user logs in and contains the user&lsquo;s identity and access rights. The JWT is then sent with every API request as a bearer token in the authorization header.</p>
      </>
    ),
  },
  {
    id: 3,
    title: "What is the difference between javascript and NodeJS?",
    content: (
      <p className="text-sm leading-relaxed">
        JavaScript and Node.js are related technologies serving different purposes in different environments. Key differences include Environment (browser vs server), Use Cases (client-side vs server-side development), APIs and Modules (DOM vs file systems/networking), Concurrency Model (event-driven in both), and Package Management (npm for both but different scopes).
      </p>
    ),
  },
  {
    id: 4,
    title: "How does NodeJS handle multiple requests at the same time?",
    content: (
      <p>Node.js handles multiple requests concurrently through its event-driven, non-blocking I/O model. It uses an event loop to manage asynchronous operations, allowing efficient handling of simultaneous requests. When a request initiates an asynchronous operation, Node.js continues processing other requests without blocking. Once completed, a callback is triggered and the event is processed, enabling Node.js to scale and handle high concurrency.</p>
    ),
  },
];
const FAQSection = () => {

  return (
    <div className="container my-5">
      <h2 className="text-3xl font-bold mb-6">Frequently Asked Questions</h2>
      <div className="space-y-3">
        {faqItems.map((item) => (
          <div key={item.id} className="collapse collapse-transition bg-black/50 text-neutral-100">
            <input type="checkbox" />
            <div className="collapse-title text-xl font-medium">
              {item.id}. {item.title}
            </div>
            <div className="collapse-content">{item.content}</div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default FAQSection;
